name: Premerge

on:
  pull_request:
  push:
    branches:
      - master

env:
  GOLANGCI_LINT_VERSION: 1.27.0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Install golangci-lint
        run: |
          mkdir -p "${HOME}/.bin"
          curl -LSs "https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_LINT_VERSION}/golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64.tar.gz" | tar --extract --gzip --strip-components=1 --dir="${HOME}/.bin" "golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64/golangci-lint"
          chmod a+x "${HOME}/.bin/golangci-lint"
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Lint
        run: PATH="${HOME}/.bin:${PATH}" golangci-lint run

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./...
